version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: nestjs_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: assignmentDb
      POSTGRES_USER: zUser
      POSTGRES_PASSWORD: zPassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
